#### Array creation

In [7]:
import numpy as np

In [2]:
# simplest form to create an elementary array is form a list
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

In [9]:
# you can specify the time of array at the creation time
a = np.array([0, 1, 2, 3], float)
a.dtype

dtype('float64')

Array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [10]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [12]:
print(a.ndim, b.ndim, c.ndim)

1 2 3


In [13]:
print(a.shape, b.shape, c.shape)

(4,) (2, 3) (2, 2, 1)


Some functions to create some standard arrays, such as filled with ones, zeros, etc

In [17]:
np.arange(1, 9, 2) # start, end (exclusive), step

array([1, 3, 5, 7])

In [18]:
np.linspace(0, 1, 6) # start, end, num-points

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
np.linspace(0, 1, 5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.ones_like(np.zeros((2, 2)))

array([[1., 1.],
       [1., 1.]])

In [25]:
np.zeros_like(np.ones((2, 2)))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.random.rand(4) # U[0, 1]

array([0.85784679, 0.68099885, 0.38337487, 0.86512695])

In [27]:
np.random.randn(4) # N(0, 1)

array([-7.60775020e-01,  1.11670089e-01, -1.08805929e+00,  9.25377679e-04])

One-dimensional versions of multi-dimensional arrays can be generated with flatten:

In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [30]:
a = np.array([1, 2], float)
b = np.array([3, 4, 5, 6], float)
c = np.array([7, 8, 9], float)

np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default (without specifying the axis), NumPy concatenates along the first dimension:

In [31]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7, 8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [32]:
np.concatenate((a, b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [33]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

### Indexing and Slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[0], a[2], a[-1]

(0, 2, 9)

In [37]:
# array order can be reserved
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
# Arrays, like other Python sequences can also be sliced:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a[2:9:3] # [start:end:step]


array([2, 5, 8])

All three slice components are not required: by default, start is 0, end is the last and step is 1:

In [41]:
a[1:3]

array([1, 2])

In [42]:
a[::2]

array([0, 2, 4, 6, 8])

In [43]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [44]:
# a more sophisticated example of multidimensional array:
a = np.arange(60).reshape((6, 10))[:, :6]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [45]:
a[0, 3:5]

array([3, 4])

In [46]:
a[4:, 5:]

array([[45],
       [55]])

In [47]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [48]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [49]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

Arrrays can be sliced using boolean logic:

In [50]:
np.random.seed(3)

In [52]:
a = np.random.randint(0, 20, 15)
a

array([17,  2,  2,  1, 19,  5,  8, 14,  1, 10,  7, 11,  1, 15, 16])

#### Array manipulations

In [55]:
# Basic operations
# with scalars

a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [56]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [57]:
# All arithmetic operates elementwise
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [58]:
a * b

array([2., 4., 6., 8.])

In [59]:
c = np.arange(5)
2**(c + 1) - c

array([ 2,  3,  6, 13, 28])

#### Other operations

In [60]:
# Comparisons
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [61]:
a == b

array([False,  True, False,  True])

In [62]:
# Array-wise comparisons:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, b)

False

#### Broadcasting

Arrays that do not match in the number of dimensions will be broadcasted by Python to perform mathematical operations. This often means that the smaller array will be repeated as necessary to perform the operation indicated. Consider the following:

In [65]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [66]:
b

array([-1.,  3.])

In [67]:
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

#### Reductions

In [68]:
a = np.array([2, 4, 3])
a.sum(), a.prod()

(9, 24)

In [69]:
np.sum(a), np.prod(a)

(9, 24)

#### Some basic statistics

In [70]:
a = np.random.randn(100)
a.mean()

-0.09744103923081739

In [71]:
np.median(a)

-0.15751010754310568

In [72]:
a.std()

1.0288326855051284

In [73]:
a.var()

1.0584966947636945

In [74]:
a.min(), a.max()

(-2.915737751792712, 2.1581493420569187)

In [75]:
np.percentile(a, [5, 50, 95])

array([-1.74994921, -0.15751011,  1.50164734])

For multidimensional arrays, each of the functions thus far described can take an optional argument axis that will perform an operation along only the specified axis, placing the results in a return array:

In [76]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a.mean(axis=0)

array([2., 2.])

In [77]:
a.mean(axis=1)

array([1., 1., 4.])

In [78]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [79]:
a.max(axis=1)

array([2., 3., 5.])

In [80]:
# Find the index of the smallest and largest element
a = np.array([2, 1, 9], float)
a.argmin()

1

In [81]:
a.argmin()

1

In [82]:
a.argmax()

2

In [83]:
# Like lists, arrays can be sorted:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [84]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

Values in an array can be “clipped” to be within a prespecified range. This is the same as applying min(max(x, minval), maxval) to each element x in an array.

In [85]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0,5)

array([5., 2., 5., 0., 0.])

In [86]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])